tpm2-software/tpm2-totp

.gitignore
INSTALL.md
Makefile.am
configure.ac

This PR applies the following recent changes to the build system from tpm2-tss:
- Support for Autoconf Archive 2019.01.06: https://github.com/tpm2-software/tpm2-tss/pull/1238, including the fix for older versions in https://github.com/tpm2-software/tpm2-tss/pull/1256
- Installation of the aclocal macros to the `m4/` subdirectory: https://github.com/tpm2-software/tpm2-tss/pull/1245

Apply build changes from tpm2-tss

---

Makefile.am
configure.ac

Currently man pages are only installed if pandoc is available on the system. Since release tarballs already include the generated man pages, the dependency on pandoc can be avoided on the target system. To do so, use the solution from tpm2-tools to have a conditional [`HAVE_MAN_PAGES`](https://github.com/tpm2-software/tpm2-tools/blob/bd188cb7fc9985081eb8b931f80d196f594539fc/configure.ac#L23) that tracks whether the folder with the generated man pages already exists.

build: install existing man pages even if pandoc is not available

---

Makefile.am

… like $(CFLAGS), unless the $(CFLAGS) of a target is specified.  In the latter
case target_CFLAGS needs to include implicitly $(AM_CFLAGS).  As the Automake
manual states:
> Adding ‘prog_CFLAGS = $(AM_CFLAGS)’ is almost a no-op, because when the ‘prog_CFLAGS’ is defined, it is used instead of ‘AM_CFLAGS’.  However as a side effect it will cause ‘prog.c’ and ‘foo.c’ to be compiled as ‘prog-prog.$(OBJEXT)’ and ‘prog-foo.$(OBJEXT)’, which solves the issue.

Makefile.am: AM_CFLAGS is used implicitly when compiling

---

configure.ac

Users assume, unless otherwise stated, that each ./configure feature has two states.  If ./configure --help prints --enable-X this implies that the feature is disabled by default.  There is no need to emit “(default: no)”.
By default, when ./configure --enable-X is called, and there is AC_ARG_ENABLE(x, …) in configure.ac, autoconf sets the variable enable_x to yes.  Likewise, when ./configure --disalbe-X is called, automake sets the variable enable_x to no.

configure.ac: remove redundant code from AC_ARG_ENABLE

---

src/libtpm2-totp.c
src/tpm2-totp.c

Some TPMs give weird errors if SHA384 is selected as a bank.
Removing it from default banks, thus only enabling SHA1 and SHA256 by default.

Remove SHA384 from default banks

---

src/libtpm2-totp.c
src/tpm2-totp.c

Building currently gives the following warnings (which fails the build
because of Werror) about format string mismatches:
src/tpm2-totp.c:343:23: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]
printf("%s%06ld", timestr, totp);
~~~~^            ~~~~
%06lld
src/libtpm2-totp.c: In function ‘tpm2totp_generateKey’:
src/libtpm2-totp.c:172:13: error: format ‘%li’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
dbg("Calling Esys_GetRandom for %li bytes", SECRETLEN - *secret_size);
~~^
%i
Fix it by using PRIu64 from inttypes.h for uint64_t and %zu for size_t.
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>

src: fix format string warnings when building for 32bit architectures

---

.travis.yml

Ubuntu Trusty 14.04 [has reached End of Life](https://blog.ubuntu.com/2019/02/05/ubuntu-14-04-trusty-tahr) and [will be replaced by Xenial as the default build environment](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment). This also allows to use the system libcurl instead of building it from source.

ci: update to Ubuntu Xenial 16.04

---

.travis.yml
INSTALL.md
Makefile.am
configure.ac
include/tpm2-totp.h
man/tpm2-totp.1.md
src/libtpm2-totp.c
src/tpm2-totp-tcti.c
src/tpm2-totp-tcti.h
src/tpm2-totp.c
test/libtpm2-totp.c
test/libtpm2-totp.sh
test/sh_log_compiler.sh
test/tpm2-totp.sh

This PR makes allows configuring the TCTI to be used with
- an additional `TSS2_TCTI_CONTEXT` argument (can be `NULL`) for the library functions and
- the new `-T`/`--tcti` option or the environment variable `TPM2TOTP_TCTI` for the tpm2-totp command.
The syntax and the implementation for the command option/environment variable follow the implementations in tpm2-tools (https://github.com/tpm2-software/tpm2-tools/pull/765, [`tpm2_options.c`](https://github.com/tpm2-software/tpm2-tools/blob/35fd340c9b29e880284a2535b210e8b97048cddc/lib/tpm2_options.c#L173) and [`tpm2_tcti_ldr.c`](https://github.com/tpm2-software/tpm2-tools/blob/35fd340c9b29e880284a2535b210e8b97048cddc/lib/tpm2_tcti_ldr.c#L80)) and tpm2-tss-engine (https://github.com/tpm2-software/tpm2-tss-engine/pull/62, …

 Make TCTI configurable and force the tests to use the simulator

---

Makefile.am
configure.ac
dist/initcpio/hooks/tpm2-totp
dist/initcpio/install/tpm2-totp

Add hooks for [mkinitcpio](https://wiki.archlinux.org/index.php/Mkinitcpio), the tool used by Arch Linux to generate initial ramdisks. The files are upstreamed from the [tpm2-totp Arch User Repository (AUR) package](https://aur.archlinux.org/packages/tpm2-totp). They are only installed if `mkinitcpio` is found on the system or `--with-mkinitcpiodir` is set explicitly to the initcpio hooks directory (`/etc/initcpio` for user files or `/usr/lib/initcpio` for packages).

dist: add mkinitcpio hooks

---

.gitignore
.travis.yml
Makefile.am
configure.ac
dist/initcpio/hooks/plymouth-tpm2-totp
dist/initcpio/install/plymouth-tpm2-totp.in
src/plymouth-tpm2-totp.c
test/plymouth-tpm2-totp.sh

This PR adds a binary `plymouth-tpm2-totp` that calculates the TOTP and displays it as a [plymouth](https://www.freedesktop.org/wiki/Software/Plymouth) message. Depending on the theme, this will look somewhat like this (the password prompt is for the disk encryption):
The application is intended to be installed and run in the background in the initial ramdisk and will automatically exit when plymouth is stopped after booting is complete.
One plymouth message with the TOTP is displayed when the application is started, after that a new message is displayed after each full 30 seconds when the TOTP changes. If there are other plymouth messages, these will overwrite the TOTP. Since this usually only happens if there are errors during boot, the user will probably want to see these instead of …

Add plymouth integration

---

.travis.yml
Makefile.am
configure.ac
test/libtpm2-totp.sh
test/mkinitcpio-tpm2-totp.sh
test/sh_log_compiler.sh
test/tpm2-totp.sh

As suggested in https://github.com/tpm2-software/tpm2-totp/pull/21#issuecomment-489558311, add a test for the mkinitcpio run hook to verify that all non-POSIX options to `read` are understood correctly. We want to do this with the BusyBox shell `/usr/lib/initcpio/busybox ash` used in initcpio ramdisks, so we need to have mkinitcpio installed for this test.
Also move the shebang to the first line in the other integration tests so that it is recognised by the kernel and we don't run into problems on systems where the default shell isn't Bash.

test: add integration test for mkinitcpio hook

---

.travis.yml

The `AX_IS_RELEASE([dash-version])` introduced in https://github.com/tpm2-software/tpm2-tools/commit/070683a551b7e94640d271f1afa39e0599c2c92d needs a more recent version of the Autoconf Archive than the one provided by the Travis Xenial VM. This fixes the current [build error](https://travis-ci.org/tpm2-software/tpm2-totp/builds/532847793).

ci: use more recent ax_is_release.m4 for tpm2-tools

---

Makefile.am
configure.ac
include/tpm2-totp.h
src/libtpm2-totp.c
src/tpm2-totp-tcti.c
src/tpm2-totp-tcti.h
src/tpm2-totp.c
test/libtpm2-totp.c
test/libtpm2-totp.sh
test/plymouth-tpm2-totp.sh
test/sh_log_compiler.sh
test/tpm2-totp.sh

The correct short identifier is BSD-3-Clause, see https://spdx.org/licenses/BSD-3-Clause.html and https://github.com/tpm2-software/tpm2-tss/pull/1394.

Fix SPDX license identifier

---

Makefile.am
include/tpm2-totp.h
src/libtpm2-totp.c
src/plymouth-tpm2-totp.c
src/tpm2-totp-tcti.c
test/libtpm2-totp.c

- `tpm2-totp.h` doesn't need to include the full [`tss2/tss2_esys.h`](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_esys.h) because it doesn't any of these functions or types, it only needs [`tss2/tss2_tcti.h`](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_tcti.h) for the `TSS2_TCTI_CONTEXT` type. Also remove some unnecessary or duplicate headers with the help of [deheader](http://www.catb.org/~esr/deheader/).
- Don't add libqrencode and libdl to every binary and library, but only to the ones that actually use them. This reduces [overlinking](http://wiki.rosalab.ru/ru/index.php/Overlinking), which can be detected using `ldd -u -r`. It doesn't fix all problems though:
- `libtpm2-totp.so` includes an unnecessary reference to …

Fix header includes and reduce overlinking

---

.travis.yml

Since https://github.com/tpm2-software/tpm2-tools/commit/893e43271024e9c2d942c8dc9ba1657a667bb0e2 tpm2-tools explicitly requires tpm2-tss >=2.3.0, so we switch to the stable version of tpm2-tools instead. We only need `tpm2_pcrextend` anyway, which didn't have any API-breaking changes.

ci: use tpm2-tools 3.X

---

src/tpm2-totp.c

Apply the patch provided by @casantos to fix #32.

src: fix compilation failure due to "variable may be used uninitialized"

---

dist/tpm2-totp.pc.in

In #31 I added tss2-mu as a dependency in preparation for https://github.com/tpm2-software/tpm2-tss/pull/1417, so it should be a private dependency (for static linking) in the pkg-config file as well.

pkg-config: add dependency on tss2-mu

---

.gitignore
Makefile.am
configure.ac
dist/dracut/module-setup.sh.in
dist/dracut/tpm2-totp.sh
dist/initcpio/install/plymouth-tpm2-totp.in

Add a [dracut](https://dracut.wiki.kernel.org/index.php/Main_Page) module to display the TOTP during boot. Since most distributions using dracut will have plymouth as well, use [plymouth-tpm2-totp](https://github.com/tpm2-software/tpm2-totp/blob/master/src/plymouth-tpm2-totp.c) for this purpose.
The module is comparable to the already existing [mkinitcpio hooks](https://github.com/tpm2-software/tpm2-totp/tree/master/dist/initcpio), but with dracut we can use udev in order to wait for the TPM to be detected by the kernel, which might help avoiding some race conditions.
Since we now detect the plymouth installation location using pkg-config, we can use this for the mkinitcpio hooks as well, making them more robust against custom installation locations. Also simplify the mkinitcpio hooks …

 dist: add dracut module for plymouth-tpm2-totp

---

configure.ac

Align with tpm2-tss to allow downstream to provide flags.

build: add --disable-defaultflags

---

dist/dracut/module-setup.sh.in
dist/initcpio/install/plymouth-tpm2-totp.in

Instead of hardcoding a path for DejaVu Sans which might not be available or in a different location, use `fc-match` to use ["the normal fontconfig matching rules to find the best font available"](https://linux.die.net/man/1/fc-match).
I am not entirely happy that we have to add `label.so` and a font manually in our hooks, this is something that either upstream plymouth or the individual distributions should do depending on the selected plymouth theme. Debian and openSUSE seem to do that, Arch and Fedora (probably, not completely sure about that) don't. Therefore we do it in our own hooks as portable as possible since possibly doing it twice won't lead to conflicts.

dist: let fontconfig choose an appropriate font

---

README.md
man/tpm2-totp.1.md

#11 removed SHA-384 from the default banks, so update the documentation to reflect that.

doc: remove SHA-384 from the default banks

---

Makefile.am

[`dracutdir`](https://github.com/tpm2-software/tpm2-totp/blob/9e68586fd4f93d9cf27d3c1bff333e3bf5e563ec/configure.ac#L103) is derived [using pkg-config](https://github.com/tpm2-software/tpm2-totp/blob/9e68586fd4f93d9cf27d3c1bff333e3bf5e563ec/configure.ac#L101), therefore it doesn't respect `${prefix}`. Hence `make distcheck` will try to install to an absolute path instead of the temporary installation directory, which usually fails without root privileges (and is not desired anyway). Fix this by providing distcheck with the default `dracutmodulesdir` path derived from `${prefix}`.

build: fix make distcheck without sudo

---

.travis.yml

Building works fine with the system OpenSSL version and we don't need to test anything specifically using OpenSSL, so save some time on the CI.
Now that OpenSSL is gone, we can also reenable ccache (#24) for a speed gain of about a minute for GCC.

ci: remove manual OpenSSL build

---

.travis.yml
configure.ac
dist/dracut/module-setup.sh.in
dist/dracut/tpm2-totp.sh
dist/initcpio/hooks/plymouth-tpm2-totp
dist/initcpio/hooks/tpm2-totp
dist/initcpio/install/plymouth-tpm2-totp.in
dist/initcpio/install/tpm2-totp.in

Since https://github.com/tpm2-software/tpm2-tss/commit/b258ab9618ded645777917a742b917a3ba72f107 `libtss2-esys.so` does not directly depend on `libtss2-tcti-device.so` any more, so we need to install the TCTI library manually to the initramfs.
The same commit moves the warning about missing TCTI libraries from the `esys` to the `tcti` module, so the `TSS2_LOG` environment variable needs to be updated as well.

dist: install tss2-tcti-device to initramfs

---

.travis.yml
Makefile.am
configure.ac
src/tpm2-totp.c

- `dist/tpm2-totp.pc` is generated by `AC_CONFIG_FILES` and therefore cleaned up automatically by Autoconf.
- As in https://github.com/tpm2-software/tpm2-tools/pull/1590, `-O2` needs to be added to the compiler flags to avoid a compilation warning/error due to fortification.
- The Autoconf Archive version in Travis CI [doesn't support `AX_ADD_FORTIFY_SOURCE`](https://travis-ci.org/tpm2-software/tpm2-totp/jobs/541382168#L1496), `ax_add_fortify_source.m4` from a newer version needs to be installed.

build: cleanup DISTCLEANFILES and add -O2

---

Makefile.am
configure.ac
dist/initramfs-tools/hooks/tpm2-totp.in
dist/initramfs-tools/scripts/init-premount/tpm2-totp

Add scripts for [initramfs-tools](https://wiki.debian.org/initramfs-tools) to display the TOTP during boot on Debian/Ubuntu/Linux Mint/... Since I don't have one of these distributions installed on bare metal, I used an initrd generated in a virtual machine running Debian 10 Buster, so this isn't extremely well tested. I verified that all necessary files are included in the initrd, that the TOTP gets displayed during boot (on my physical machine) and that the `rd.tpm2-totp.nvindex` kernel command line option works as expected.
Closes: #41

 dist: add initramfs-tools scripts for plymouth-tpm2-totp

---

INSTALL.md
Makefile.am
README.md
dist/dracut/README

- Mention the initramfs hooks in [README](https://github.com/tpm2-software/tpm2-totp/blob/master/README.md) and in [INSTALL](https://github.com/tpm2-software/tpm2-totp/blob/master/INSTALL.md) so that people know that they exist and how to install them.
- The new [tpm2-totp(3) man page](https://github.com/tpm2-software/tpm2-totp/pull/42) optionally requires doxygen during build.
- Add a README to the dracut module because that seems to be common practice. The text is largely taken from the [help text of the mkinitcpio hook](https://github.com/tpm2-software/tpm2-totp/blob/master/dist/initcpio/install/tpm2-totp.in).

Documentation updates

---

src/plymouth-tpm2-totp.c
src/tpm2-totp.c

Fix the alerts reported by [LGTM](https://lgtm.com/projects/g/tpm2-software/tpm2-totp/snapshot/25e778746b1774d3b549e066f36362da34f98ba3/files/src/plymouth-tpm2-totp.c#x23c0813f6532bb09:1): using the reentrant version of standard library functions is generally safer (though not strictly necessary since we are not using multithreading at the moment).

src: replace localtime by localtime_r

---

dist/dracut/tpm2-totp.sh
dist/initcpio/hooks/plymouth-tpm2-totp
dist/initcpio/hooks/tpm2-totp
dist/initramfs-tools/scripts/init-premount/tpm2-totp

Since tpm2-tss 2.3.0 (https://github.com/tpm2-software/tpm2-tss/commit/727fc47ea15941c29bac993c39fb1d2e5987f9ac) messages about missing TCTI libraries like libtss2-tcti-default.so have log level DEBUG and are therefore hidden from the logging output by default, hence we can remove our custom log level setting. Since #53 we only support tpm2-tss>=2.3 anyway, so backwards compatibility is not a concern here.

dist: remove TSS2_LOG=tcti+error

---

src/tpm2-totp.c
test/tpm2-totp.sh

`tcti_context` needs to be initialised so that `Tss2_TctiLdr_Finalize` can be called safely in case of errors. Also add an integration test with an invalid argument to catch this issue in the future.

tpm2-totp: fix segfault for invalid command line arguments

---

configure.ac

The variable name was wrong, resulting in an empty display at all times:
```
tpm2-totp 0.2.0_rc0
doxygen:         
pandoc:          /usr/bin/pandoc
dracut:          /usr/lib/dracut/modules.d
initramfs-tools: 
mkinitcpio:      ${prefix}/etc/initcpio
plymouth:        yes
```

build: fix doxygen status display in configure

---

Makefile.am
dist/dracut/module-setup.sh.in

Since commit 38ca58575fc7b964e60e30457859020df2ba0fe6 the dracut module works without plymouth as well, so install it whenever dracut is available.
`plymouth-tpm2-totp` might not be available even if plymouth is installed if tpm2-totp was built on a system without plymouth. Fall back to the version without plymouth in this case, which is guaranteed to exist if the dracut module is installed. In this case the TOTP is not shown in the graphical boot screen, but can be seen after pressing the <kbd>Esc</kbd> key.
Also remove `dist/initcpio/install/tpm2-totp` from the distribution tarball because it is autogenerated from [`dist/initcpio/install/tpm2-totp.in`](https://github.com/tpm2-software/tpm2-totp/blob/master/dist/initcpio/install/tpm2-totp.in).

build: install dracut module if plymouth is not available

---

Makefile.am

`module-setup.sh` [copies `show-tpm2-totp` from `helpersdir`](https://github.com/tpm2-software/tpm2-totp/blob/b3efaec7266b2c8717dc7107b941d8284a67cd62/dist/dracut/module-setup.sh.in#L22), so the script needs to be put there (as [it is done for mkinitcpio](https://github.com/tpm2-software/tpm2-totp/blob/b3efaec7266b2c8717dc7107b941d8284a67cd62/Makefile.am#L196) as well) instead of `dracutdir`.

dist: fix installation location of show-tpm2-totp for dracut

---

src/libtpm2-totp.c

Fix the following build failure with musl:
```
src/libtpm2-totp.c: In function ‘tpm2totp_calculate’:
src/libtpm2-totp.c:826:11: warning: implicit declaration of function ‘htobe64’ [-Wimplicit-function-declaration]
tmp = htobe64(tmp);
^~~~~~~
```
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

src/libtpm2-totp.c: include <endian.h>

---

dist/dracut/show-tpm2-totp.sh

The dollar sign is a [special character in udev rules](https://www.freedesktop.org/software/systemd/man/udev.html#Rules%20Files) and must be escaped as `$$`, otherwise `journalctl -b` shows the following warning:
```
/etc/udev/rules.d/80-tpm2-totp.rules:1 Invalid value "/sbin/initqueue --settled --onetime /bin/show-tpm2-totp & show_tpm2_totp_pid=$!" for RUN (char 79: invalid substitution type),ignoring, but please fix it.
```
This hopefully fixes #65.

dist: escape "$" in dracut udev rule

---

src/tpm2-totp.c

They're functionally equivalent for the escape character, as \e is
really \033 as it's ASCII value, but it's a little more compact and
clear to use \e.
Signed-off-by: William Roberts <william.c.roberts@intel.com>

qrencode: use \e instead of \033

---

INSTALL.md
configure.ac
test/sh_log_compiler.sh

`libtss2-tcti-swtpm` is available in tpm2-tss 3.0.0. Keep support for `libtss2-tcti-mssim` to allow running the integration tests with older tpm2-tss versions as well, but prefer swtpm if it is available.

test: add support for swtpm simulator

---

Makefile.am
configure.ac
src/libtpm2-totp.c
src/tpm2-totp.c

I thought I had submitted this ages ago, but apparently I didn't... Add some custom error messages for frequent problems like trying to call `tpm2-totp calculate` twice, being unable to calculate the TOTP after a change in PCRs etc. If none of the custom error messages are applicable, fall back to the messages from tss2-rc instead of displaying a raw response code.
Closes: #61

tpm2-totp: display more specific messages for common error cases

---

.travis.yml

Support for swtpm was already added in #69, so switching the simulator in Travis CI is straightforward, also see https://github.com/tpm2-software/tpm2-tss-engine/pull/193.

ci: switch from ibmswtpm to swtpm

---

Makefile.am
configure.ac
dist/initcpio/install/sd-plymouth-tpm2-totp.in
dist/plymouth-tpm2-totp.service.in

mkinitcpio supports two different kinds of initramfs images: one with a busybox init (`HOOKS=(base udev ...)`) and one with a systemd init (`HOOKS=(systemd sd-...)`). Only the former supports the runtime hooks in [`dist/initcpio/hooks`](https://github.com/tpm2-software/tpm2-totp/tree/master/dist/initcpio/hooks) that we use to start `show-`/`plymouth-tpm2-totp`, the latter relies on system unit files to start programs.
This commit adds a new mkinitcpio hook `sd-plymouth-tpm2-totp` to be used for systemd-based mkinitcpio initramfs images. It adds a systemd service `plymouth-tpm2-totp.service` that triggers `plymouth-tpm2-totp` once Plymouth has been started and `/dev/tpm0` is available. While the hook itself is specific to mkinitcpio, this service might be useful for other systemd-based …

dist: add sd-plymouth-tpm2-totp mkinitcpio hook

---

test/libtpm2-totp.c

The correct format specifier for uint64_t is PRIu64.
fixes these compilation issues on my rpi:
```
test/libtpm2-totp.c:49:39: error: format ‘%ld’ expects argument of type
‘long int’, but argument 5 has type ‘uint64_t’ {aka ‘long long unsigned
int’} [-Werror=format=]
snprintf(&totp_string[0], 7, "%.*ld", 6, totp);
~~~~^      ~~~~
%.*lld
test/libtpm2-totp.c:66:39: error: format ‘%ld’ expects argument of type
‘long int’, but argument 5 has type ‘uint64_t’ {aka ‘long long unsigned
int’} [-Werror=format=]
snprintf(&totp_string[0], 7, "%.*ld", 6, totp);
~~~~^      ~~~~
%.*lld
```
Signed-off-by: Peter Huewe <Peter.Huewe@infineon.com>

print uint64_t using inttypes.h `PRIu64` instead of `ld`

---

Makefile.am

When building tpm2-totp with slibtool (https://dev.midipix.org/cross/slibtool) it fails.
```
rdlibtool --tag=CC --mode=link clang -I./include -I./src -std=c99 -Wall -Wextra -Wformat-security -Werror -fstack-protector-all -fpic -fPIC -O2 -Wno-missing-braces -I/usr/include/tss2 -I/usr/include/tss2 -g -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro (tpm2_totp) -o libtpm2-totp.la -rpath /usr/local/lib src/libtpm2-totp.lo -ltss2-esys -ltss2-mu
rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/tpm2-totp"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 34, .st_ino = 375651}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = 3.
rdlibtool: lconf: found "/tmp/tpm2-totp/libtool".
rdlibtool: link: ar crs .libs/libtpm2-totp.a …
```

build: Remove bogus value from Makefile.am.

---

Doxyfile.in
configure.ac

Update `configure.ac` and `Doxyfile.in` to remove some obsolete, unused options that cause deprecation warnings log spam.

build: remove some obsolete options

---

.ci/coverity.run
.github/workflows/coverity.yml
README.md

Enable coverity runs on the [`coverity_scan`](https://github.com/tpm2-software/tpm2-totp/tree/coverity_scan) branch (project was already created and successfully analysed, cf. https://scan.coverity.com/projects/tpm2-totp) and add a badge to the README file.

ci: enable coverity

---

Makefile.am

The same issue that has been fixed in #44 for `dracutmodulesdir` has resurfaced for `systemdsystemunitdir`: since it is derived using pkg-config, it doesn't respect `${prefix}`, making `make distcheck` fail (or install directly to the system directory instead of `DESTDIR` if invoked as root). Provide a value for `systemdsystemunitdir` derived from `${prefix}` that is used for distcheck.

build: provide default value of systemdsystemunitdir for make distcheck

---

README.md
dist/dracut/README
dist/dracut/module-setup.sh.in
dist/initcpio/install/plymouth-tpm2-totp.in
dist/initcpio/install/sd-plymouth-tpm2-totp.in
dist/initcpio/install/sd-tpm2-totp.in
dist/initcpio/install/tpm2-totp.in
dist/show-tpm2-totp
dist/tpm2-totp.service.in
man/tpm2-totp.1.md
src/tpm2-totp.c
test/plymouth-tpm2-totp.sh
test/tpm2-totp.sh

addresses #87
Introduces breaking changes in CLI API, so maybe earmark for v1.0

Cli redesign

---

README.md
man/tpm2-totp.1.md
src/tpm2-totp.c
test/tpm2-totp.sh

fixes #86
At the moment, this forbids `\0` in input stream, but allows `\n`, etc. Not sure if we want to restrict `--password` to single-line, printable ASCII only, or arbitrary binary secrets (and what about `\0` in that case).

Password from stdin

---

dist/tpm2-totp.service.in
dist/tpm2-totp.timer.in

Change Requires= to Wants= for systemd-vconsole-setup.service. This allows
showing a code even if the vconsole setup fails (for example, because of a bad
font or bad keymap).

dist: show TOTP even if vconsole setup fails
